### ISSUE TITLE
Невозможно авторизоваться

### ISSUE THREAD

**Issue by ponomarchukov** [jack-theripper/yandex#30]
Fatal error: Uncaught Arhitector\Yandex\Client\Exception\UnauthorizedException: Не авторизован. in C:\xampp2\htdocs\ph\vendor\arhitector\yandex\src\Client\OAuth.php:278 Stack trace: #0 C:\xampp2\htdocs\ph\vendor\arhitector\yandex\src\AbstractClient.php(145): Arhitector\Yandex\Client\OAuth->transformResponseToException(Object(Zend\Diactoros\Request), Object(Zend\Diactoros\Response)) #1 C:\xampp2\htdocs\ph\vendor\arhitector\yandex\src\Disk.php(525): Arhitector\Yandex\AbstractClient->send(Object(Zend\Diactoros\Request)) #2 C:\xampp2\htdocs\ph\vendor\arhitector\yandex\src\Disk.php(257): Arhitector\Yandex\Disk->send(Object(Zend\Diactoros\Request)) #3 [internal function]: Arhitector\Yandex\Disk->Arhitector\Yandex\{closure}(Array) #4 C:\xampp2\htdocs\ph\vendor\arhitector\yandex\src\Disk\Resource\Collection.php(56): call_user_func(Object(Closure), Array) #5 C:\xampp2\htdocs\ph\vendor\arhitector\yandex\src\Client\Container\Collection.php(42): Arhitector\Yandex\Disk\Resource\Collection->toArray() #6 C:\xampp2\htdocs\ph in C:\xampp2\htdocs\ph\vendor\arhitector\yandex\src\Client\OAuth.php on line 278

**Comment by jack-theripper** [comment]
@oliwin 

[Как-подключиться-к-ЯндексДиску](https://github.com/jack-theripper/yandex#12-%D0%9A%D0%B0%D0%BA-%D0%BF%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B8%D1%82%D1%8C%D1%81%D1%8F-%D0%BA-%D0%AF%D0%BD%D0%B4%D0%B5%D0%BA%D1%81%D0%94%D0%B8%D1%81%D0%BA%D1%83)

```php
$client = new Arhitector\Yandex\Client\OAuth('OAuth-токен');
```

**Comment by ezirl** [comment]
Тоже тупил немного, после создания приложения над токен еще получить по адресу 
https://oauth.yandex.ru/authorize?response_type=token&client_id=идентификатор приложения
Пароль из приложения не есть OAuth-токен.
